In [22]:
import numpy as np
a = np.array([1,3,5,7,9])
print(a)
print (a[4])

[1 3 5 7 9]
9


In [2]:
a = np.array([[1, 2], [3, 4],[5,6]]) 
print(a)
print(a.dtype)

[[1 2]
 [3 4]
 [5 6]]
int32


In [3]:
print(a.ndim)
print(a.itemsize)

2
4


In [4]:
import numpy as np 
a = np.array([5,6,9], dtype = complex) 
print(a)

print(a.dtype)

[5.+0.j 6.+0.j 9.+0.j]
complex128


In [5]:
print(a.itemsize)
print(a.size)
print(a.shape)


16
3
(3,)


In [6]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)


[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [7]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
print(np.where(arr==4))

(array([3, 5, 6], dtype=int64),)


In [8]:
a = np.array([[1, 2], [3, 4],[5,6]]) 
print(a.shape)

(3, 2)


In [9]:
print(np.arange(2,10,2))
print(a.reshape(2,3))

[2 4 6 8]
[[1 2 3]
 [4 5 6]]


In [10]:
print(a.ravel())

[1 2 3 4 5 6]


In [11]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [12]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [13]:
for cell in a.flat:
    print(cell)

a=np.arange(6).reshape(3,2)
print(a)    
b=np.arange(6,12).reshape(3,2)
print(np.vstack((a,b))) # Stacking Along columns  vstack function
print(np.hstack((a,b))) # Stacking Along Rows  hstack function

1
2
3
4
5
6
[[0 1]
 [2 3]
 [4 5]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


In [14]:
print(a.min())
print(a.max())
print(a.sum())
print(np.sqrt(a))
print(np.std(a))

0
5
15
[[0.         1.        ]
 [1.41421356 1.73205081]
 [2.         2.23606798]]
1.707825127659933


In [15]:
a = np.array([[1,2,6], [3,4,9],[5,6,8]]) 
print(a)

print(a[0:2,2])
print(a[-2])


[[1 2 6]
 [3 4 9]
 [5 6 8]]
[6 9]
[3 4 9]


In [16]:
a=np.arange(30).reshape(2,15)
print(a)
result=np.vsplit(a,2)
print(result[0])
print(result[1])
b=a>10
print(b)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
[[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]
[[False False False False False False False False False False False  True
   True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True
   True  True  True]]


In [17]:
for x in np.nditer(a, op_flags = ['readwrite']):
   x[...] = 2*x
print(a)

[[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
 [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58]]


In [18]:
#copy
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()                # Not affect the original array
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [19]:
#View
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()               # Change the Original array
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [20]:
x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[42  2  3  4  5]


In [21]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)
arr = np.stack((arr1, arr2), axis=1)

print(arr)

[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
